version: "3.1"
services:
  db:
    image: mysql:5.7
    container_name: project_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: pybo
      MYSQL_PASSWORD: pybo100
      MYSQL_ROOT_PASSWORD: toor
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./home/user/mysqldb/datadir:/var/lib/mysql
